sass:
  style: expanded

markdown: kramdown
# kramdown:
#   input: GFM
#   auto_ids: true
#   toc_levels: 1..3
#
#   # https://kramdown.gettalong.org/syntax_highlighter/rouge.html
#   syntax_highlighter: rouge
#   syntax_highlighter_opts: # https://github.com/rouge-ruby/rouge#full-options
#     css_class: highlight # CSS classes for code blocks
#     #formatter: MyFormatter
#     #default_lang: console
#     #guess_lang: unknown
#     #disable: false
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true # Displays the line number in the code block
#       start_line: 1 # Displays the line number in the code block
#       line_class: lineno
#       table_class: rouge-table # - CSS class of table block, default: rouge-table
#       gutter_class: rouge-gutter # - CSS class of line number, default: rouge-gutter
#       code_class: rouge-code # - CSS class of code content,  default: rouge-code
